# Generated by Django 3.0.8 on 2020-08-13 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.TextField(max_length=512)),
                ('comment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date commented')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date liked')),
            ],
            options={
                'verbose_name': 'Like',
                'verbose_name_plural': 'Likes',
            },
        ),
        migrations.CreateModel(
            name='UserFollowing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_content', models.TextField(max_length=512)),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date posted')),
                ('post_comments', models.ManyToManyField(blank=True, related_name='Post', to='network.Comment')),
                ('post_likes', models.ManyToManyField(blank=True, related_name='Post', to='network.Like')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='comments_owner',
            field=models.ManyToManyField(blank=True, related_name='owner', to='network.Comment'),
        ),
        migrations.AddField(
            model_name='user',
            name='likes_owner',
            field=models.ManyToManyField(blank=True, related_name='owner', to='network.Like'),
        ),
        migrations.AddField(
            model_name='user',
            name='posts_owner',
            field=models.ManyToManyField(blank=True, related_name='owner', to='network.Post'),
        ),
    ]
